import * as rpg from '../controller/rpg.js'

export const COLD='cold' //ice, tundras...
export const DESERT='desert' //low-vegetation
export const INFERNO='inferno' //lava, magma, steam...
export const LUSH='lush' //heavy vegetation
export const ROCKY='rocky' //exposed rock, some vegetation...
export const WATER='water' //bodies of water, beaches...
export const ORBITAL='orbital' //anything with an outer-space background

export const INDUSTRIAL='industrial' //heavy machinery, pavement...
export const URBAN='urban' //buildings, roads...

export const TEMPLE='temple'//natural spaces with with lower-tech or sparse improvements and buildings
export const DARK='dark' //stylized, neon-heavy, creepy...
export const TOXIC='toxic' //anything that looks poisonous, radioactive...

const DEBUG=false

class ScMap{
  constructor(players,name,themes){
    this.players=players
    this.name=name
    this.themes=themes
  }
  
  toString(){return this.name}
}

var players=[]
export var maps=[
  new ScMap(2,"16-bit",[ORBITAL]),
  new ScMap(2,"2000 atmospheres",[WATER]),
  new ScMap(2,"abiogenesis",[LUSH,ROCKY]),
  new ScMap(2,"abyssal reef",[WATER]),
  new ScMap(2,"acid plant",[INDUSTRIAL]),
  new ScMap(2,"acolyte",[DARK,ROCKY]),
  new ScMap(2,"agria valley",[LUSH]),
  new ScMap(2,"akilon flats",[ROCKY]),
  new ScMap(2,"akilon wastes",[DESERT]),
  new ScMap(2,"apotheosis",[ROCKY]),
  new ScMap(2,"arid plateau",[DESERT]),
  new ScMap(2,"ascension to aiur",[TEMPLE]),
  new ScMap(2,"automaton",[DARK,INDUSTRIAL]),
  new ScMap(2,"backwater",[WATER]),
  new ScMap(2,"bamboozle",[LUSH]),
  new ScMap(2,"battle on the boardwalk",[DESERT]),
  new ScMap(2,"beckett industries",[INDUSTRIAL,INFERNO]),
  new ScMap(2,"bel'shir vestige",[LUSH]),
  new ScMap(2,"blackburn",[DARK]),
  new ScMap(2,"blistering sands",[DESERT]),
  new ScMap(2,"bloodboil",[COLD]),
  new ScMap(2,"blueshift",[DESERT]),
  new ScMap(2,"burial grounds",[TEMPLE]),
  new ScMap(2,"catalyst",[DESERT,ROCKY]),
  new ScMap(2,"acropolis",[URBAN,LUSH,ROCKY]),
  new ScMap(2,"bridgehead",[LUSH]),
  new ScMap(2,"cerulean fall",[ROCKY]),
  new ScMap(2,"cloud kingdom",[ROCKY]),
  new ScMap(2,"coda",[DESERT]),
  new ScMap(2,"crossfire",[LUSH]),
  new ScMap(2,"cyber forest",[LUSH]),
  new ScMap(2,"daedalus point",[DARK]),
  new ScMap(2,"dasan station",[COLD,ROCKY]),
  new ScMap(2,"dash and terminal",[INDUSTRIAL,ORBITAL]),
  new ScMap(2,"daybreak",[ORBITAL]),
  new ScMap(2,"deathaura",[LUSH]),
  new ScMap(2,"defender's landing",[ORBITAL]),
  new ScMap(2,"derelict watcher",[ORBITAL]),
  new ScMap(2,"desert oasis",[DESERT]),
  new ScMap(2,"disco bloodbath",[URBAN]),
  new ScMap(2,"dreamcatcher",[TEMPLE,LUSH]),
  new ScMap(2,"dusk towers",[INDUSTRIAL]),
  new ScMap(2,"eastwatch",[ROCKY,TEMPLE]),
  new ScMap(2,"echo",[INDUSTRIAL]),
  new ScMap(2,"ephemeron",[LUSH]),
  new ScMap(2,"ethernal empire",[DESERT]),
  new ScMap(2,"eternal scar",[ROCKY,LUSH]),
  new ScMap(2,"ever dream",[ROCKY]),
  new ScMap(2,"expedition lost",[COLD]),
  new ScMap(2,"fracture",[COLD]),
  new ScMap(2,"frozen temple",[COLD,TEMPLE]),
  new ScMap(2,"galactic process",[ORBITAL]),
  new ScMap(2,"golden wall",[ROCKY]),
  new ScMap(2,"habitation station",[INDUSTRIAL,URBAN]),
  new ScMap(2,"heavy rain",[LUSH,ROCKY]),
  new ScMap(2,"howling peak",[COLD]),
  new ScMap(2,"ice and chrome",[COLD]),
  new ScMap(2,"incineration zone",[INFERNO]),
  new ScMap(2,"interloper",[WATER,LUSH]),
  new ScMap(2,"jagannatha",[TEMPLE,LUSH]),
  new ScMap(2,"jungle basin",[LUSH]),
  new ScMap(2,"junk yard",[ROCKY]),
  new ScMap(2,"kairos junction",[ROCKY,DESERT]),
  new ScMap(2,"king sejong station",[COLD]),
  new ScMap(2,"king's cove",[WATER]),
  new ScMap(2,"klontas mire",[TOXIC]),
  new ScMap(2,"korhal compound",[ROCKY]),
  new ScMap(2,"lightshade",[COLD]),
  new ScMap(2,"lost and found",[DARK]),
  new ScMap(2,"mech depot",[INDUSTRIAL,LUSH]),
  new ScMap(2,"moonloight madness",[INFERNO]),
  new ScMap(2,"neo planet",[ORBITAL,COLD]),
  new ScMap(2,"neo seoul",[URBAN,INDUSTRIAL]),
  new ScMap(2,"neon violet square",[URBAN,DARK]),
  new ScMap(2,"new gettysburg",[URBAN]),
  new ScMap(2,"new repugnancy",[URBAN]),
  new ScMap(2,"newkirk district",[URBAN]),
  new ScMap(2,"newkirk precint",[URBAN]),
  new ScMap(2,"nightshade",[DARK]),
  new ScMap(2,"odyssey",[WATER]),
  new ScMap(2,"ohana",[WATER]),
  new ScMap(2,"orbital shipyard",[ORBITAL]),
  new ScMap(2,"overgrowth",[LUSH]),
  new ScMap(2,"oxide",[ROCKY]),
  new ScMap(2,"paladino terminal",[URBAN,ROCKY]),
  new ScMap(2,"para site",[WATER]),
  new ScMap(2,"pillars of gold",[DESERT]),
  new ScMap(2,"polar night",[COLD]),
  new ScMap(2,"port aleksander",[URBAN]),
  new ScMap(2,"prion terraces",[URBAN]),
  new ScMap(2,"proxima station",[URBAN]),
  new ScMap(2,"purity and industry",[ORBITAL]),
  new ScMap(2,"redshift",[COLD]),
  new ScMap(2,"romaticide",[DARK]),
  new ScMap(2,"ruins of endion",[ROCKY]),
  new ScMap(2,"scrap station",[ORBITAL]),
  new ScMap(2,"secret spring",[WATER]),
  new ScMap(2,"sequencer",[ORBITAL]),
  new ScMap(2,"simulacrum",[URBAN,INDUSTRIAL]),
  new ScMap(2,"star station",[ORBITAL]),
  new ScMap(2,"stasis",[ORBITAL]),
  new ScMap(2,"steppes of war",[LUSH]),
  new ScMap(2,"submarine",[WATER]),
  new ScMap(2,"terraform",[LUSH]),
  new ScMap(2,"thunderbird",[ROCKY]),
  new ScMap(2,"triton",[COLD]),
  new ScMap(2,"turbo cruise '84",[URBAN]),
  new ScMap(2,"ulrena",[URBAN]),
  new ScMap(2,"vaani research station",[ROCKY]),
  new ScMap(2,"winter's gate",[COLD]),
  new ScMap(2,"world of sleepers",[ORBITAL]),
  new ScMap(2,"worldship",[ORBITAL]),
  new ScMap(2,"xel'naga caverns",[ROCKY]),
  new ScMap(2,"year zero",[ROCKY]),
  new ScMap(2,"yeonsu",[LUSH,COLD]),
  new ScMap(2,"zen le",[LUSH]),
  new ScMap(3,"catallena",[WATER]),
  new ScMap(3,"elysium",[ROCKY]),
  new ScMap(3,"merry go round",[ORBITAL]),//TODO ?  
  new ScMap(4,"abyssal caverns",[WATER,ROCKY]),
  new ScMap(4,"alterzim stronghold",[DARK]),
  new ScMap(4,"antiga shipyard",[ORBITAL]),
  new ScMap(4,"arctic dream",[COLD]),
  new ScMap(4,"actic gates",[COLD]),
  new ScMap(4,"arid wastes",[DESERT]),
  new ScMap(4,"avalanche",[COLD]),
  new ScMap(4,"backwater gulch",[WATER]),
  new ScMap(4,"cactus valley",[DESERT]),
  new ScMap(4,"central protocol",[ORBITAL]),
  new ScMap(4,"condemned ridge",[ROCKY]),
  new ScMap(4,"crooked maw",[TOXIC]),
  new ScMap(4,"crystal pools",[ROCKY]),
  new ScMap(4,"darkness sanctuary",[DARK,TEMPLE]),
  new ScMap(4,"deadwing",[DARK]),
  new ScMap(4,"debris field",[ORBITAL]),
  new ScMap(4,"delta quadrant",[ORBITAL]),
  new ScMap(4,"desert refuge",[DESERT]),
  new ScMap(4,"desolate stronghold",[ROCKY]),
  new ScMap(4,"discord iv",[ORBITAL]),
  new ScMap(4,"divergence",[ORBITAL]),
  new ScMap(4,"dusty gorge",[DESERT]),
  new ScMap(4,"efforescence",[LUSH]),
  new ScMap(4,"emerald city",[DARK]),
  new ScMap(4,"entombed valley",[ROCKY]),
  new ScMap(4,"fields of death",[INFERNO]),
  new ScMap(4,"flooded city",[WATER]),
  new ScMap(4,"foxtrot labs",[INDUSTRIAL]),
  new ScMap(4,"fracture glacier",[COLD]),
  new ScMap(4,"frost",[COLD]),
  new ScMap(4,"geosync quarry",[ORBITAL]),
  new ScMap(4,"graystone ravine",[DESERT]),
  new ScMap(4,"gutterhulk",[ORBITAL]),
  new ScMap(4,"heavy artillery",[ROCKY]),
  new ScMap(4,"high orbit",[ORBITAL]),
  new ScMap(4,"honorgrounds",[LUSH,ROCKY]),
  new ScMap(4,"inferno pools",[INFERNO]),
  new ScMap(4,"infestation",[INFERNO]),
  new ScMap(4,"invader",[URBAN]),
  new ScMap(4,"iron fortress",[TEMPLE,URBAN]),
  new ScMap(4,"isle of slaughter",[TOXIC]),
  new ScMap(4,"katherine square",[URBAN]),
  new ScMap(4,"khaydarin depths",[COLD]),
  new ScMap(4,"korhal city",[URBAN]),
  new ScMap(4,"korhal sky island",[URBAN]),
  new ScMap(4,"kulas ravine",[LUSH]),
  new ScMap(4,"lerilak crest",[ROCKY]),
  new ScMap(4,"lost temple",[LUSH,TEMPLE]),
  new ScMap(4,"lunar colony v",[ROCKY]),
  new ScMap(4,"magma mines",[INFERNO]),
  new ScMap(4,"metalopolis",[URBAN]),
  new ScMap(4,"metropolis",[URBAN]),
  new ScMap(4,"molten crater",[INFERNO]),
  new ScMap(4,"monlyth ridge",[ROCKY,DESERT]),
  new ScMap(4,"narazim crypt",[DARK,TEMPLE]),
  new ScMap(4,"new antloch",[DARK]),
  new ScMap(4,"nightmare",[INFERNO]),
  new ScMap(4,"nightscape",[DARK]),
  new ScMap(4,"nimbus",[INDUSTRIAL]),
  new ScMap(4,"omega sector",[ORBITAL]),
  new ScMap(4,"omicron",[URBAN]),
  new ScMap(4,"overgown facility",[LUSH]),
  new ScMap(4,"polka",[LUSH,TOXIC]),
  new ScMap(4,"preservation",[URBAN]),
  new ScMap(4,"reclamation",[DARK]),
  new ScMap(4,"red city",[DARK,ROCKY,INDUSTRIAL]),
  new ScMap(4,"red stone gulch",[ROCKY]),
  new ScMap(4,"redstorm",[INFERNO]),
  new ScMap(4,"reflection",[COLD]),
  new ScMap(4,"resupply tanker",[INDUSTRIAL,WATER]),
  new ScMap(4,"rhoskallian",[INDUSTRIAL,DESERT]),
  new ScMap(4,"ruins of seras",[LUSH]),
  new ScMap(4,"scorched haven",[INFERNO]),
  new ScMap(4,"searing crater",[INFERNO]),
  new ScMap(4,"seeds of aiur",[TEMPLE]),
  new ScMap(4,"seething jungle",[ROCKY]),
  new ScMap(4,"shadowed jungle",[DARK,INDUSTRIAL]),
  new ScMap(4,"shakiras plateau",[ROCKY]),
  new ScMap(4,"shrines of lizul",[TEMPLE,ROCKY]),
  new ScMap(4,"slag pits",[ROCKY]),
  new ScMap(4,"sludge city",[TOXIC,INDUSTRIAL]),
  new ScMap(4,"snowy mesa",[COLD,ROCKY]),
  new ScMap(4,"star station",[ORBITAL]),
  new ScMap(4,"tal'darim altar",[LUSH,TEMPLE]),
  new ScMap(4,"tarsonis assault",[ROCKY,DESERT]),
  new ScMap(4,"terminus",[ORBITAL]),
  new ScMap(4,"the bone trench",[INFERNO]),
  new ScMap(4,"the ruins of tarsonis",[DESERT]),
  new ScMap(4,"the shattered temple",[LUSH,TEMPLE]),
  new ScMap(4,"traitor's exile",[DARK]),
  new ScMap(4,"twilight fortress",[DARK]),
  new ScMap(4,"typhon peaks",[ROCKY]),
  new ScMap(4,"ulzaan",[ORBITAL]),
  new ScMap(4,"vigilance",[ORBITAL]),
  new ScMap(4,"war zone",[ROCKY]),
  new ScMap(4,"waystation",[ORBITAL]),
  new ScMap(4,"whirlwind",[LUSH]),
  new ScMap(4,"wolfe industries compound",[INDUSTRIAL,URBAN]),
  new ScMap(4,"zerus prime",[INFERNO]),  
  new ScMap(6,"abandoned camp",[ROCKY,URBAN]),
  new ScMap(6,"aftermath",[URBAN]),
  new ScMap(6,"arakan citadel",[LUSH]),
  new ScMap(6,"augustine fall",[URBAN]),
  new ScMap(6,"avalon labs",[INDUSTRIAL]),
  new ScMap(6,"backcountry",[LUSH]),
  new ScMap(6,"backwater complex",[INDUSTRIAL]),
  new ScMap(6,"bastion of the conclave",[URBAN]),
  new ScMap(6,"black site",[INDUSTRIAL]),
  new ScMap(6,"bone temple",[TEMPLE]),
  new ScMap(6,"buried caverns",[COLD,ROCKY]),
  new ScMap(6,"burning tide",[INFERNO]),
  new ScMap(6,"canyon of tribulation",[LUSH,ROCKY]),
  new ScMap(6,"cinder fortress",[INFERNO]),
  new ScMap(6,"colony 426",[WATER]),
  new ScMap(6,"descent",[DARK]),
  new ScMap(6,"dig site",[DARK]),
  new ScMap(6,"dirt side",[DESERT]),
  new ScMap(6,"doraelus hills",[LUSH]),
  new ScMap(6,"dust bowl",[DESERT]),
  new ScMap(6,"fields of shazir",[COLD]),
  new ScMap(6,"flashback",[TEMPLE]),
  new ScMap(6,"forbidden sanctuary",[TEMPLE]),
  new ScMap(6,"frontier",[COLD,ROCKY]),
  new ScMap(6,"froenze fields",[COLD]),
  new ScMap(6,"green acres",[LUSH]),
  new ScMap(6,"hills of peshkov",[LUSH]),
  new ScMap(6,"ice cliffs",[COLD]),
  new ScMap(6,"jungle depths",[LUSH]),
  new ScMap(6,"misty swamp",[DARK,LUSH]),
  new ScMap(6,"molten temple",[INFERNO]),
  new ScMap(6,"monsoon",[LUSH]),
  new ScMap(6,"nephor",[URBAN]),
  new ScMap(6,"new richmond",[URBAN]),
  new ScMap(6,"new williamsberg",[URBAN]),
  new ScMap(6,"orbital depot",[ORBITAL]),
  new ScMap(6,"queen's nest",[TOXIC]),
  new ScMap(6,"quicksand",[DESERT]),
  new ScMap(6,"realities simulation",[LUSH,ROCKY]),
  new ScMap(6,"research complex",[INDUSTRIAL]),
  new ScMap(6,"rosebud",[DARK,TEMPLE]),
  new ScMap(6,"sands of strife",[DESERT]),
  new ScMap(6,"scorched vista",[WATER]),
  new ScMap(6,"sentinel",[TEMPLE,LUSH]),
  new ScMap(6,"shadow reactor",[INDUSTRIAL]),
  new ScMap(6,"silent dunes",[WATER]),
  new ScMap(6,"slaying fields",[TEMPLE]),
  new ScMap(6,"snowbound colony",[COLD]),
  new ScMap(6,"stranded isles",[WATER,LUSH]),
  new ScMap(6,"tectonic rift",[INFERNO]),
  new ScMap(6,"temple of the preservers",[TEMPLE]),
  new ScMap(6,"the bio lab",[ORBITAL]),
  new ScMap(6,"the commune",[URBAN]),
  new ScMap(6,"twisted vern",[DARK]),
  new ScMap(6,"typhon",[ROCKY]),
  new ScMap(6,"tyrador keep",[ROCKY,COLD]),
  new ScMap(6,"ujari",[DARK]),
  new ScMap(6,"ulaan deeps",[COLD]),
  new ScMap(6,"untamed spire",[LUSH]),
  new ScMap(6,"vaults of secrets",[DARK]),
  new ScMap(6,"whitewater line",[DARK]),
  new ScMap(8,"abandoned parish",[TEMPLE,LUSH]),
  new ScMap(8,"abyss",[DARK,ROCKY]),
  new ScMap(8,"alaeni enclave",[URBAN]),
  new ScMap(8,"asper mountain",[ROCKY,LUSH]),
  new ScMap(8,"atlas station",[ORBITAL]),
  new ScMap(8,"blackfrost extraction",[COLD]),
  new ScMap(8,"celestial bastion",[ORBITAL]),
  new ScMap(8,"concord",[TEMPLE,LUSH]),
  new ScMap(8,"conduit",[DARK]),
  new ScMap(8,"cryptic fortress",[DARK]),
  new ScMap(8,"deadlook ridge",[ROCKY]),
  new ScMap(8,"distant plane",[ORBITAL]),
  new ScMap(8,"district 10",[URBAN]),
  new ScMap(8,"extinction",[DESERT]),
  new ScMap(8,"fallout zone",[URBAN]),
  new ScMap(8,"forbidden planet",[DESERT]),
  new ScMap(8,"forgotten sanctuary",[TEMPLE]),
  new ScMap(8,"fortitude",[INFERNO]),
  new ScMap(8,"fossil quarry",[ROCKY,INDUSTRIAL]),
  new ScMap(8,"garden of shadows",[DARK]),
  new ScMap(8,"halcyon",[URBAN]),
  new ScMap(8,"hidden caves",[COLD,DESERT]),
  new ScMap(8,"high ground",[DARK]),
  new ScMap(8,"hunting ground",[LUSH]),
  new ScMap(8,"kimeran refuge",[ORBITAL]),
  new ScMap(8,"korhaul carange knockout",[URBAN]),
  new ScMap(8,"last impact",[URBAN]),
  new ScMap(8,"last remnant",[DESERT]),
  new ScMap(8,"lava flow",[INFERNO]),
  new ScMap(8,"lexiphanicism",[INDUSTRIAL,DESERT]),
  new ScMap(8,"magma core",[INFERNO]),
  new ScMap(8,"megaton",[LUSH]),
  new ScMap(8,"mementos",[DARK]),
  new ScMap(8,"moebius facility",[ORBITAL]),
  new ScMap(8,"multiprocessor",[ORBITAL]),
  new ScMap(8,"nekodrec",[DESERT,INDUSTRIAL]),
  new ScMap(8,"old country",[ROCKY]),
  new ScMap(8,"old estate",[URBAN]),
  new ScMap(8,"outpost",[URBAN]),
  new ScMap(8,"overwatch",[URBAN]),
  new ScMap(8,"primevals wilds",[INFERNO,LUSH,ROCKY]),
  new ScMap(8,"primordial grave",[DESERT]),
  new ScMap(8,"refinery",[INDUSTRIAL]),
  new ScMap(8,"research site",[ORBITAL]),
  new ScMap(8,"retribution",[INDUSTRIAL]),
  new ScMap(8,"rooftop terrace",[URBAN]),
  new ScMap(8,"sacred grounds",[TEMPLE]),
  new ScMap(8,"sand canyon",[DESERT]),
  new ScMap(8,"scoria reactor",[INFERNO]),
  new ScMap(8,"shattered terrace",[LUSH]),
  new ScMap(8,"shipwrecked",[WATER]),
  new ScMap(8,"sky harvester",[DESERT,INDUSTRIAL]),
  new ScMap(8,"sunderer isle",[INFERNO]),
  new ScMap(8,"sunset valley",[LUSH]),
  new ScMap(8,"tempest",[LUSH]),
  new ScMap(8,"the boneyard",[DESERT]),
  new ScMap(8,"toxic slums",[TOXIC]),
  new ScMap(8,"troizinia",[LUSH]),
  new ScMap(8,"tropic shores",[WATER]),
  new ScMap(8,"tuonela",[INFERNO]),
  new ScMap(8,"void zone",[ORBITAL]),
  new ScMap(8,"volcanic ridge",[INFERNO]),
  new ScMap(8,"whirling morass",[ROCKY]),
  new ScMap(8,"zenith",[DARK]),
]

export function filter(themes){
  let pool=[]
  for(let m of maps)
    for(let t of m.themes)
      if(themes.indexOf(t)>=0){
        pool.push(m)
        break
      }
  return pool
}

if(DEBUG){
  let total=0
  let themes=[COLD,DESERT,INFERNO,LUSH,ROCKY,WATER,
    INDUSTRIAL,ORBITAL,TEMPLE,URBAN,DARK,TOXIC]
  for(let t of themes){
    let nmaps=maps.filter(
      a=>a.themes.indexOf(t)>=0).length
    total+=nmaps
    console.log(`${nmaps} ${t} maps`)
  }
  console.log(maps.length+' total maps')
}
