//TODO looks like it would be possible to organize by terrain: desert, forest, aquatic, urban, orbital, temple, etc. would be cool to have each campaign generate a planet with cumulative 50% chance of 1+1 terrains. 
import * as rpg from './rpg.js'

export var maps=[]//arrays of map names by number of players
var players=[]

maps[2]=["16-bit","2000 atmospheres","abiogenesis","abyssal reef","acid plant","acolyte","agria valley","akilon flats","akilon wastes","apotheosis","arid plateau","ascension to aiur","automaton","backwater","bamboozle","battle on the boardwalk","beckett industries","bel'shir vestige","blackburn","blistering sands","bloodboil","blueshift","burial grounds","catalyst","cerulean fall","cloud kingdom","coda","crossfire","cyber forest","daedalus point","dasan station","dash and terminal","daybreak","deathaura","defender's landing","derelict watcher","desert oasis","disco bloodbath","dreamcatcher","dusk towers","eastwatch","echo","ephemeron","ethernal empire","eternal scar","ever dream","expedition lost","fracture","frozen temple","galactic process","golden wall","habitation station","heavy rain","howling peak","ice and chrome","incineration zone","interloper","jagannatha","jungle basin","junk yard","kairos junction","king sejong station","king's cove","klontas mire","korhal compound","lightshade","lost and found","mech depot","moonloight madness","neo planet s","neo seoul","neon violet square","new gettysburg","new repugnancy","newkirk district","newkirk precint","nightshade","odyssey","ohana","orbital shipyard","overgrowth","oxide","paladino terminal","para site","pillars of gold","polar night","port aleksander","prion terraces","proxima station","purity and industry","redshift","romaticide","ruins of endion","scrap station","secret spring","sequencer","simulacrum","star station","stasis","steppes of war","submarine","terraform","thunderbird","triton","turbo cruise '84","ulrena","vaani research station","winter's gate","world of sleepers","worldship","xel'naga caverns","year zero","yeonsu","zen le"]
maps[3]=["catallena","elysium","merry go round"]
maps[4]=["abyssal caverns","alterzim stronghold","antiga shipyard","arctic dream","actic gates","arid wastes","avalanche","backwater gulch","cactus valley","central protocol","condemned ridge","crooked maw","crystal pools","darkness sanctuary","deadwing","debris field","delta quadrant","desert refuge","desolate stronghold","discord iv","divergence","dusty gorge","efforescence","emerald city","entombed valley","fields of death","flooded city","foxtrot labs","fracture glacier","frost","geosync quarry","graystone ravine","gutterhulk","heavy artillery","high orbit","honorgrounds","inferno pools","infestation","invader","iron fortress","isle of slaughter","katherine square","khaydarin depths","korhal city","korhal sky island","kulas ravine","lerilak crest","lost temple","lunar colony v","magma mines","metalopolis","molten crater","monlyth ridge","narazim crypt","new antloch","nightmare","nightscape","nimbus","omega sector","omicron","overgown facility","polka","preservation","reclamation","red city","red stone gulch","redstorm","reflection","resupply tanker","rhoskallian","ruins of seras","scorched haven","searing crater","seeds of aiur","seething jungle","shadowed jungle","shakiras plateau","shrines of lizul","slag pits","sludge city","snowy mesa","star station","tal'darim altar","tarsonis assault","terminus","the bone trench","the ruins of tarsonis","the shattered temple","traitor's exile","twilight fortress","typhon peaks","ulzaan","vigilance","war zone","waystation","whirlwind","wolfe industries compound","zerus prime"]
maps[6]=["abandoned camp","aftermath","arakan citadel","augustine fall","avalon labs","backcountry","backwater complex","bastion of the conclave","black site","bone temple","buried caverns","burning tide","canyon of tribulation","cinder fortress","colony 426","descent","dig site","dirt side","doraelus hills","dust bowl","fields of shazir","flashback","forbidden sanctuary","frontier","froenze fields","green acres","hills of peshkov","ice cliffs","jungle depths","misty swamp","molten temple","monsoon","nephor","new richmond","new williamsberg","orbital depot","queen's nest","quicksand","realities simulation","research complex","rosebud","sands of strife","scorched vista","sentinel","shadow reactor","silent dunes","slaying fields","snowbound colony","stranded isles","tectonic rift","temple of the preservers","the bio lab","the commune","twisted vern","typhon","tyrador keep","ujari","ulaan deeps","untamed spire","vaults of secrets","whitewater line"]
maps[8]=["abandoned parish","abyss","alaeni enclave","asper mountain","atlas station","blackfrost extraction","celestial bastion","concord","conduit","cryptic fortress","deadlook ridge","distant plane","district 10","extinction","fallout zone","forbidden planet","forgotten sanctuary","fortitude","fossil quarry","garden of shadows","halcyon","hidden caves","high ground","hunting ground","kimeran refuge","korhaul carange knockout","last impact","last remnant","lava flow","lexiphanicism","magma core","megaton","mementos","moebius facility","multiprocessor","nekodrec","old country","old estate","outpost","overwatch","primevals wilds","primordial grave","refinery","research site","retribution","rooftop terrace","sacred grounds","sand canyon","scoria reactor","shattered terrace","shipwrecked","sky harvester","sunderer isle","sunset valley","tempest","the boneyard","toxic slums","troizinia","tropic shores","tuonela","void zone","volcanic ridge","whirling morass","zenith"]

export function get(nplayers){
  if(nplayers<2) nplayers=2
  let pool=Array.from(Object.keys(maps))
    .map(n=>parseInt(n))
    .filter(n=>nplayers<=n&&n<=nplayers*2)
    .flatMap(n=>new Array(maps[n].length).fill(n))
  pool=rpg.pick(pool)
  let map=rpg.roll(0,maps[pool].length-1)
  return maps[pool].splice(map,1)[0]
}
